/**
 * Handlers for Candidate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: automl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AutomlDomainModule } from "../dependencies/automl-ddd.dependencies.js";
import type { GetCandidateInput, ListCandidatesInput } from "@scorvia/services/automl";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/automl-runs/{runId}/candidates
 * Operation: listCandidates
 */
export async function listCandidates(
  request: FastifyRequest<{ Params: { runId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AutomlDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCandidatesInput = {
    runId: request.params.runId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.candidates.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/candidates/{candidateId}
 * Operation: getCandidate
 */
export async function getCandidate(
  request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AutomlDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCandidateInput = {
    candidateId: request.params.candidateId,
  };
  const result = await deps.useCases.candidates.get.execute(input);
  return reply.code(200).send(result);
}


