/**
 * GetPolicyMap handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getPolicyMap } from "@scorvia/api-server/domains/policy/handlers";
import type { PolicyDDDDependencies } from "@scorvia/api-server/domains/policy";
import { createPolicyMap as createPolicyMapEntity } from "@scorvia/factories/policy";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@scorvia/tests/shared";
import { POLICY_USE_CASES } from "../__factories__/use-cases.js";

describe("GetPolicyMap", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PolicyDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PolicyDDDDependencies>(
      POLICY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createPolicyMapEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetPolicyMap, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { policyMapId: entity.id };

    await getPolicyMap(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetPolicyMap.execute).toHaveBeenCalledWith(expect.objectContaining({ policyMapId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { policyMapId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetPolicyMap, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getPolicyMap(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
