/**
 * Project Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ProjectEntity } from "@scorvia/core/projects/models/index.js";
import { projectsSchemas } from "@scorvia/core/projects";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prj";

export function createProject(overrides: Partial<ProjectEntity> = {}) {
  const raw = {
    id: overrides.id ?? `prj_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    environment: overrides.environment ?? "poc",
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "draft",
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return projectsSchemas.CreditProject.parse(raw);
}

export function projectBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createProject(overrides));
}
