/**
 * DisposeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisposeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DisposeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DisposeRepository,
} from "@scorvia/services/monitoring";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DisposeRepositoryDdb } from "./dispose-repository.ddb.js";

/**
 * DisposeRepositoryAdapter
 *
 * Implements DisposeRepository port for infrastructure layer.
 */
export class DisposeRepositoryAdapter implements DisposeRepository {
  private readonly ddb: DisposeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DisposeRepositoryDdb(this.dynamoClient);
  }

  async disposeMonitoringIncident(input: Parameters<DisposeRepository['disposeMonitoringIncident']>[0]): Promise<Awaited<ReturnType<DisposeRepository['disposeMonitoringIncident']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.disposeMonitoringIncident(input);
  }
}
