/**
 * IncidentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IncidentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements IncidentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  IncidentRepository,
} from "@scorvia/services/monitoring";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { IncidentRepositoryDdb } from "./incident-repository.ddb.js";

/**
 * IncidentRepositoryAdapter
 *
 * Implements IncidentRepository port for infrastructure layer.
 */
export class IncidentRepositoryAdapter implements IncidentRepository {
  private readonly ddb: IncidentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new IncidentRepositoryDdb(this.dynamoClient);
  }

  async listMonitoringIncidents(input: Parameters<IncidentRepository['listMonitoringIncidents']>[0]): Promise<Awaited<ReturnType<IncidentRepository['listMonitoringIncidents']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listMonitoringIncidents(input);
  }

  async openMonitoringIncident(input: Parameters<IncidentRepository['openMonitoringIncident']>[0]): Promise<Awaited<ReturnType<IncidentRepository['openMonitoringIncident']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openMonitoringIncident(input);
  }
}
