/**
 * Handlers for InterpretabilityPack
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EvaluationsDomainModule } from "../dependencies/evaluations-ddd.dependencies.js";
import type { AttachInterpretabilityPackInput } from "@scorvia/services/evaluations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/candidates/{candidateId}/interpretability-packs
 * Operation: attachInterpretabilityPack
 */
export async function attachInterpretabilityPack(
  request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EvaluationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AttachInterpretabilityPackInput = {
    candidateId: request.params.candidateId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.interpretabilityPacks.get.execute(input);
  return reply.code(201).send(result);
}


