/**
 * ProjectRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProjectRepositoryDdb
 *
 * DDD: Infrastructure adapter implementing Project repository using DynamoDB.
 * Generated from x-dynamodb metadata in OpenAPI schema.
 */

import type { ProjectRepository } from "@scorvia/services/projects";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { getCoreTableName, getBaseTableName, getAnalyticsTableName } from "../_shared/dynamodb-utils.js";
import { sanitizeItem } from "../_shared/dynamodb-key-helpers.js";
import { ulid } from "ulid";

/**
 * ProjectRepositoryDdb using DynamoDB table (type: core)
 *
 * Entity Type: CREDIT_PROJECT
 * Entity Token: CREDIT_PROJECT
 * SK Prefix: CREDIT_PROJECT
 */
export class ProjectRepositoryDdb implements ProjectRepository {
  private readonly TABLE_NAME: string;
  // Metadata from x-dynamodb annotation - all values are dynamic
  private readonly ENTITY_TYPE = "CREDIT_PROJECT";
  private readonly ENTITY_TOKEN = "CREDIT_PROJECT";
  private readonly SK_PREFIX = "CREDIT_PROJECT";
  private readonly IS_CHILD_ENTITY = false;
  private readonly CREATED_AT_FIELD = "createdAt";
  private readonly UPDATED_AT_FIELD = "updatedAt";
  private readonly SOFT_DELETE_ENABLED = false;
  private readonly DOMAIN = "PROJECTS";
  private readonly ENTITY_TYPE_PK = "CREDIT_PROJECTS";
  private generateCorrelationId(): string {
    const domainPrefix = "prj";
    return `${domainPrefix}_${ulid().toLowerCase()}`;
  }
  /** Partition key from x-dynamodb: ORG#orgId#DOMAIN#COLLECTION#entityId (id in PK). */
  private buildPK(orgId: string, entityId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}#${entityId}`;
  }
  /** Collection prefix for list/query: ORG#orgId#DOMAIN#COLLECTION (no entityId). */
  private getCollectionPK(orgId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}`;
  }
  /** Deterministic SK: ENTITY#entityId (legacy …#TIMESTAMP#ts dual-read via begins_with). */
  private buildSK(entityId: string, _identifier?: string): string {
    return `${this.ENTITY_TOKEN}#${entityId}`;
  }
  /** GSI time SK: updatedAt#entityId (uniqueness under bulk writes). */
  private buildGsiSK(updatedAt: string, entityId: string): string {
    return `${updatedAt}#${entityId}`;
  }
  /** GSI2 list-by-org: ORG#orgId#COLLECTION */
  private buildGSI2PK(orgId: string): string {
    return `ORG#${orgId}#${this.ENTITY_TYPE_PK}`;
  }


  constructor(private readonly dynamoClient: AdapterDynamoDBClient) {
    const tableTypeFromMetadata = "core";
    const tableTypeMap = {
      core: getCoreTableName,
      base: getBaseTableName,
      analytics: getAnalyticsTableName,
    };
    const tableNameFn = tableTypeMap[tableTypeFromMetadata] || getCoreTableName;
    this.TABLE_NAME = tableNameFn();
  }

  async listCreditProjects(input: Parameters<ProjectRepository['listCreditProjects']>[0]): Promise<Awaited<ReturnType<ProjectRepository['listCreditProjects']>>> {
    const inputExt = input as Record<string, unknown>;

    if (!input) {
      throw new Error("Missing required parameter: input");
    }
    if (!inputExt.orgId) {
      throw new Error("Missing required parameter: orgId");
    }
    const gsi2PK = `ORG#${inputExt.orgId}#${this.ENTITY_TYPE_PK}`;
    const rawLimit = inputExt?.limit;
    const parsedLimit = rawLimit == null || rawLimit === ""
      ? 50
      : (typeof rawLimit === "string" ? parseInt(rawLimit as string, 10) : Number(rawLimit));
    const limit = Number.isFinite(parsedLimit) && parsedLimit > 0 ? parsedLimit : 50;
    const result = await this.dynamoClient.query({
      TableName: this.TABLE_NAME,
      IndexName: "GSI2",
      KeyConditionExpression: "#gsi2pk = :pk",
      ExpressionAttributeNames: { "#gsi2pk": "GSI2-PK" },

      ExpressionAttributeValues: {
        ":pk": gsi2PK,
      },
      Limit: limit,
      ScanIndexForward: false,
      ...((() => {
        const c = inputExt?.cursor;
        if (!c || (typeof c === "string" && !c.trim())) return {};
        try {
          return {
            ExclusiveStartKey: typeof c === "string"
              ? JSON.parse(Buffer.from(c, "base64").toString())
              : c,
          };
        } catch {
          return {};
        }
      })()),
    });
    const items = ((result.Items || []) as Record<string, unknown>[]).map((i) => sanitizeItem(i));
    return {
      data: { items: items } as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
        pagination: {
          nextCursor: result.LastEvaluatedKey ? Buffer.from(JSON.stringify(result.LastEvaluatedKey)).toString("base64") : null,
          prevCursor: null,
          limit: inputExt?.limit || 50,
        },
      } as unknown as any,
    };
  }

  async createCreditProject(input: Parameters<ProjectRepository['createCreditProject']>[0]): Promise<Awaited<ReturnType<ProjectRepository['createCreditProject']>>> {
    const inputExt = input as Record<string, unknown>;

    const now = new Date().toISOString();
    const orgId = inputExt.orgId;
    const id = inputExt?.id ?? inputExt?.id;
    if (!id) throw new Error("Missing required parameter: id (inject from use case)");
    const pk = this.buildPK(orgId as string, id as string);
    const sk = this.buildSK(id as string);
    const excludedFields = ["id" as string, "id"];
    const inputWithoutId = Object.fromEntries(
      Object.entries(input || {}).filter(([key]) => !excludedFields.includes(key))
    );
    const item = {
      ...inputWithoutId,
      id: id,
      PK: pk,
      SK: sk,
      entityType: this.ENTITY_TYPE,
      [this.CREATED_AT_FIELD]: now,
      [this.UPDATED_AT_FIELD]: now,
      "GSI2-PK": this.buildGSI2PK(orgId as string),
      "GSI2-SK": this.buildGsiSK(now, id as string),
    };
    await this.dynamoClient.put({
      TableName: this.TABLE_NAME,
      Item: item,
      ConditionExpression: "attribute_not_exists(PK) AND attribute_not_exists(SK)",
    });
    return {
      data: sanitizeItem(item as Record<string, unknown>) as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
      } as unknown as any,
    };
  }

  async getCreditProject(input: Parameters<ProjectRepository['getCreditProject']>[0]): Promise<Awaited<ReturnType<ProjectRepository['getCreditProject']>>> {
    const inputExt = input as Record<string, unknown>;

    if (!input) {
      throw new Error("Missing required parameter: input");
    }
    if (!(inputExt.id ?? inputExt.projectId)) {
      throw new Error("Missing required parameter: id");
    }
    if (!inputExt.orgId) {
      throw new Error("Missing required parameter: orgId");
    }
    const pk = this.buildPK(inputExt.orgId as string, (inputExt.id ?? inputExt.projectId) as string);
    // Soft-delete layout prefixes SK with ACTIVE# when statusPrefix is enabled.
    const skPrefix = `${this.ENTITY_TOKEN}#${(inputExt.id ?? inputExt.projectId)}#`;
    const result = await this.dynamoClient.query({
      TableName: this.TABLE_NAME,
      KeyConditionExpression: "PK = :pk AND begins_with(SK, :skPrefix)",
      ExpressionAttributeValues: { ":pk": pk, ":skPrefix": skPrefix },
      Limit: 1,
    });
    const item = result.Items?.[0];
    if (!item) {
      throw new Error(`${this.ENTITY_TYPE} with id ${(inputExt.id ?? inputExt.projectId)} not found`);
    }
    return {
      data: sanitizeItem(item as Record<string, unknown>) as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
      } as unknown as any,
    };
  }
}
