/**
 * StartAutoMLRun handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: automl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { startAutoMLRun } from "@scorvia/api-server/domains/automl/handlers";
import type { AutomlDDDDependencies } from "@scorvia/api-server/domains/automl";
import { createAutomlRun as createAutomlRunEntity } from "@scorvia/factories/automl";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@scorvia/tests/shared";
import { AUTOML_USE_CASES } from "../__factories__/use-cases.js";

describe("StartAutoMLRun", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AutomlDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AutomlDDDDependencies>(
      AUTOML_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createAutomlRunEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeStartAutoMLRun, "execute").mockResolvedValue(useCaseResult);

    await startAutoMLRun(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeStartAutoMLRun.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
