/**
 * Promotions DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Promotions Domain Module - Composition root
 *
 * DDD: Composition root for promotions domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DecideRepositoryAdapter,
  PromotionRepositoryAdapter,
} from "@scorvia/adapters/promotions";
import { getIdGeneratorService } from "@scorvia/adapters";
import type { AdapterDynamoDBClient } from "@scorvia/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteDecidePromotion,
  ExecuteGetPromotion,
  ExecuteListPromotions,
  ExecuteRequestPromotion,
} from "@scorvia/services/promotions/usecases";
// Ports (interfaces)
import type {
  DecideRepository,
  PromotionRepository,
} from "@scorvia/services/promotions/ports";

export interface PromotionsDomainModule {
  repos: {
    decides: DecideRepository;
    promotions: PromotionRepository;
  };
  useCases: {
    decides: {
      get: ExecuteDecidePromotion;
    };
    promotions: {
      get: ExecuteGetPromotion;
      list: ExecuteListPromotions;
    };
  };
}

export function buildPromotionsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): PromotionsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      decides?: DecideRepository;
      promotions?: PromotionRepository;
    } = {};

    obj.decides = new DecideRepositoryAdapter(dynamoClient);
    obj.promotions = new PromotionRepositoryAdapter(dynamoClient);
    return {
      decides: obj.decides!,
      promotions: obj.promotions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    decides: {
      get: new ExecuteDecidePromotion(executionContext, idGenerator, repos.decides),
    },
    promotions: {
      get: new ExecuteGetPromotion(executionContext, idGenerator, repos.promotions),
      list: new ExecuteListPromotions(executionContext, idGenerator, repos.promotions),
    },
  };
  return { repos, useCases: useCases as PromotionsDomainModule["useCases"] };
}
