/**
 * ListPromotion DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListPromotionsParams } from "@scorvia/core/promotions";

export function createListPromotionRequest(overrides: Partial<ListPromotionsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
