/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Monitoring Domain Use Cases
 * 
 * List of all use case names for the monitoring domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const MONITORING_USE_CASES = [
  "executeDisposeMonitoringIncident",
  "executeListMonitoringIncidents",
  "executeOpenMonitoringIncident"
] as const;
