/**
 * ListExport DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAuditExportsParams } from "@scorvia/core/audits";

export function createListExportRequest(overrides: Partial<ListAuditExportsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
