/**
 * Dispose Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DisposeEntity } from "@scorvia/core/monitoring/models/index.js";
import { monitoringSchemas } from "@scorvia/core/monitoring";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mon";

export function createDispose(overrides: Partial<DisposeEntity> = {}) {
  const raw = {
    id: overrides.id ?? `mon_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    deploymentId: overrides.deploymentId ?? faker.string.uuid(),
    incidentType: overrides.incidentType ?? "drift",
    status: overrides.status ?? "open",
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return monitoringSchemas.MonitoringIncident.parse(raw);
}

export function disposeBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDispose(overrides));
}
