/**
 * ExecuteAttachInterpretabilityPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAttachInterpretabilityPack Use Case
 *
 * DDD: Application use case for get InterpretabilityPack.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AttachInterpretabilityPackInput, AttachInterpretabilityPackOutput } from "../dto/interpretability-pack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { InterpretabilityPackRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAttachInterpretabilityPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly interpretabilityPack: InterpretabilityPackRepository
  ) {}

  async execute(input: AttachInterpretabilityPackInput): Promise<AttachInterpretabilityPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.evlId();

    // All field names extracted from OpenAPI spec: adverseActionFactors, artefactUri, narrative
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).candidateId) {
      throw new ValidationError("candidateId is required");
    }
    const candidateId = (input as any).candidateId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.interpretabilityPack.attachInterpretabilityPack({ candidateId: candidateId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${candidateId}`);
    }

    return entity as AttachInterpretabilityPackOutput;
  }
}
