/**
 * Project DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Project DTOs
 *
 * DDD: Application DTOs for Project use cases.
 */

import type { CreateCreditProjectRequestInput, GetCreditProjectParams, ListCreditProjectsParams } from "@scorvia/core/projects/types";

export type ListCreditProjectsInput = ListCreditProjectsParams;

export type CreateCreditProjectInput = CreateCreditProjectRequestInput;

export type GetCreditProjectInput = GetCreditProjectParams;

export type ListCreditProjectsOutput = {};

export type CreateCreditProjectOutput = {};

export type GetCreditProjectOutput = {};
