/**
 * ScoreRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScoreRepository Port
 *
 * DDD: Application port for scorerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ScoreApplicationInput, ScoreApplicationOutput } from "../dto/score.dto";
export interface ScoreRepository {
  scoreApplication(input: ScoreApplicationInput): Promise<ScoreApplicationOutput>;
}

export type { ScoreApplicationInput, ScoreApplicationOutput } from "../dto/score.dto";
