/**
 * Handlers for Decide
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PromotionsDomainModule } from "../dependencies/promotions-ddd.dependencies.js";
import type { DecidePromotionInput } from "@scorvia/services/promotions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/promotions/{promotionId}/decide
 * Operation: decidePromotion
 */
export async function decidePromotion(
  request: FastifyRequest<{ Params: { promotionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PromotionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DecidePromotionInput = {
    promotionId: request.params.promotionId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.decides.get.execute(input);
  return reply.code(200).send(result);
}


