/**
 * Handlers for Promotion
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PromotionsDomainModule } from "../dependencies/promotions-ddd.dependencies.js";
import type { GetPromotionInput, ListPromotionsInput, RequestPromotionInput } from "@scorvia/services/promotions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/candidates/{candidateId}/promotions
 * Operation: requestPromotion
 */
export async function requestPromotion(
  request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PromotionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RequestPromotionInput = {
    candidateId: request.params.candidateId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.promotions.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/promotions
 * Operation: listPromotions
 */
export async function listPromotions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PromotionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPromotionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.promotions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/promotions/{promotionId}
 * Operation: getPromotion
 */
export async function getPromotion(
  request: FastifyRequest<{ Params: { promotionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PromotionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPromotionInput = {
    promotionId: request.params.promotionId,
  };
  const result = await deps.useCases.promotions.get.execute(input);
  return reply.code(200).send(result);
}


