/**
 * ReferralRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReferralRepository Port
 *
 * DDD: Application port for referralrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetReferralInput, GetReferralOutput, ListReferralsInput, ListReferralsOutput } from "../dto/referral.dto";
export interface ReferralRepository {
  listReferrals(input: ListReferralsInput): Promise<ListReferralsOutput>;
  getReferral(input: GetReferralInput): Promise<GetReferralOutput>;
}

export type { GetReferralInput, GetReferralOutput, ListReferralsInput, ListReferralsOutput } from "../dto/referral.dto";
