/**
 * Handlers for Deployment
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ScoringDomainModule } from "../dependencies/scoring-ddd.dependencies.js";
import type { ListDeploymentsInput } from "@scorvia/services/scoring";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/scoring/deployments
 * Operation: listDeployments
 */
export async function listDeployments(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ScoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDeploymentsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.deployments.list.execute(input);
  return reply.code(200).send(result);
}


