/**
 * Monitoring DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Monitoring Domain Module - Composition root
 *
 * DDD: Composition root for monitoring domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DisposeRepositoryAdapter,
  IncidentRepositoryAdapter,
} from "@scorvia/adapters/monitoring";
import { getIdGeneratorService } from "@scorvia/adapters";
import type { AdapterDynamoDBClient } from "@scorvia/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteDisposeMonitoringIncident,
  ExecuteListMonitoringIncidents,
  ExecuteOpenMonitoringIncident,
} from "@scorvia/services/monitoring/usecases";
// Ports (interfaces)
import type {
  DisposeRepository,
  IncidentRepository,
} from "@scorvia/services/monitoring/ports";

export interface MonitoringDomainModule {
  repos: {
    disposes: DisposeRepository;
    incidents: IncidentRepository;
  };
  useCases: {
    disposes: {
      get: ExecuteDisposeMonitoringIncident;
    };
    incidents: {
      get: ExecuteOpenMonitoringIncident;
      list: ExecuteListMonitoringIncidents;
    };
  };
}

export function buildMonitoringDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): MonitoringDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      disposes?: DisposeRepository;
      incidents?: IncidentRepository;
    } = {};

    obj.disposes = new DisposeRepositoryAdapter(dynamoClient);
    obj.incidents = new IncidentRepositoryAdapter(dynamoClient);
    return {
      disposes: obj.disposes!,
      incidents: obj.incidents!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    disposes: {
      get: new ExecuteDisposeMonitoringIncident(executionContext, idGenerator, repos.disposes),
    },
    incidents: {
      get: new ExecuteOpenMonitoringIncident(executionContext, idGenerator, repos.incidents),
      list: new ExecuteListMonitoringIncidents(executionContext, idGenerator, repos.incidents),
    },
  };
  return { repos, useCases: useCases as MonitoringDomainModule["useCases"] };
}
