/**
 * ListDeployment DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListDeploymentsParams } from "@scorvia/core/scoring";

export function createListDeploymentRequest(overrides: Partial<ListDeploymentsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
