/**
 * ExecuteRequestPromotion - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRequestPromotion Use Case
 *
 * DDD: Application use case for get Promotion.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RequestPromotionInput, RequestPromotionOutput } from "../dto/promotion.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { PromotionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRequestPromotion {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly promotion: PromotionRepository
  ) {}

  async execute(input: RequestPromotionInput): Promise<RequestPromotionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prmId();

    // All field names extracted from OpenAPI spec: interpretabilityUri, monitoringPlanUri, notes
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).candidateId) {
      throw new ValidationError("candidateId is required");
    }
    const candidateId = (input as any).candidateId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.promotion.requestPromotion({ candidateId: candidateId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${candidateId}`);
    }

    return entity as RequestPromotionOutput;
  }
}
