/**
 * ExecuteListPromotions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPromotions Use Case
 *
 * DDD: Application use case for list Promotion.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPromotionsInput, ListPromotionsOutput } from "../dto/promotion.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { PromotionRepository } from "../ports";

export class ExecuteListPromotions {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly promotion: PromotionRepository
  ) {}

  async execute(input: ListPromotionsInput): Promise<ListPromotionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prmId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.promotion.listPromotions({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPromotionsOutput;
  }
}
