/**
 * Policy Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createPolicyMap_Body = z
  .object({
    name: z.string(),
    bands: z.array(
      z
        .object({
          minPd: z.number(),
          maxPd: z.number(),
          decision: z.enum(['grant', 'refer', 'deny']),
          pricingBand: z.string().optional(),
        })
        .passthrough()
    ),
    projectId: z.string().optional(),
    referralRequired: z.boolean().optional().default(true),
  })
  .passthrough();
const simulatePolicyMap_Body = z
  .object({ pdValues: z.array(z.number()) })
  .passthrough();

export const schemas: any = {
  createPolicyMap_Body,
  simulatePolicyMap_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/policy-maps',
    alias: 'listPolicyMaps',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
                  tenantId: z.string().regex(/^tnt_[0-9A-HJKMNP-TV-Z]{26}$/),
                  name: z.string(),
                  status: z.enum(['draft', 'published', 'retired']),
                  version: z.number().int(),
                  bands: z
                    .array(
                      z
                        .object({
                          minPd: z.number(),
                          maxPd: z.number(),
                          decision: z.enum(['grant', 'refer', 'deny']),
                          pricingBand: z.string().optional(),
                        })
                        .passthrough()
                    )
                    .optional(),
                  referralRequired: z.boolean().optional(),
                  projectId: z.string().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/policy-maps',
    alias: 'createPolicyMap',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createPolicyMap_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
            tenantId: z.string().regex(/^tnt_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            status: z.enum(['draft', 'published', 'retired']),
            version: z.number().int(),
            bands: z
              .array(
                z
                  .object({
                    minPd: z.number(),
                    maxPd: z.number(),
                    decision: z.enum(['grant', 'refer', 'deny']),
                    pricingBand: z.string().optional(),
                  })
                  .passthrough()
              )
              .optional(),
            referralRequired: z.boolean().optional(),
            projectId: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 422,
        description: `Semantically invalid request (e.g. PACK_EMPTY)`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/policy-maps/:policyMapId',
    alias: 'getPolicyMap',
    requestFormat: 'json',
    parameters: [
      {
        name: 'policyMapId',
        type: 'Path',
        schema: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
            tenantId: z.string().regex(/^tnt_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            status: z.enum(['draft', 'published', 'retired']),
            version: z.number().int(),
            bands: z
              .array(
                z
                  .object({
                    minPd: z.number(),
                    maxPd: z.number(),
                    decision: z.enum(['grant', 'refer', 'deny']),
                    pricingBand: z.string().optional(),
                  })
                  .passthrough()
              )
              .optional(),
            referralRequired: z.boolean().optional(),
            projectId: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/policy-maps/:policyMapId/publish',
    alias: 'publishPolicyMap',
    requestFormat: 'json',
    parameters: [
      {
        name: 'policyMapId',
        type: 'Path',
        schema: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
            tenantId: z.string().regex(/^tnt_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            status: z.enum(['draft', 'published', 'retired']),
            version: z.number().int(),
            bands: z
              .array(
                z
                  .object({
                    minPd: z.number(),
                    maxPd: z.number(),
                    decision: z.enum(['grant', 'refer', 'deny']),
                    pricingBand: z.string().optional(),
                  })
                  .passthrough()
              )
              .optional(),
            referralRequired: z.boolean().optional(),
            projectId: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/policy-maps/:policyMapId/simulate',
    alias: 'simulatePolicyMap',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: simulatePolicyMap_Body,
      },
      {
        name: 'policyMapId',
        type: 'Path',
        schema: z.string().regex(/^pol_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            grantCount: z.number().int(),
            referCount: z.number().int(),
            denyCount: z.number().int(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
