/**
 * Repository interface for Resolve
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ResolveEntity
} from "../models/resolve.entity.js";
import type {
  Referral
} from "../types/index.js";
/**
 * ResolveRepository Interface
 */
export interface ResolveRepository extends CreateReadRepository<ResolveEntity, Referral, string, Record<string, never>> {

}
