/**
 * Score DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Score DTOs
 *
 * DDD: Application DTOs for Score use cases.
 */

import type { ScoreApplicationRequestInput } from "@scorvia/core/scoring/types";

export type ScoreApplicationInput = ScoreApplicationRequestInput;

export type ScoreApplicationOutput = {};
