/**
 * ExecuteGetAutoMLRun - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: automl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetAutoMLRun Use Case
 *
 * DDD: Application use case for get AutomlRun.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetAutoMLRunInput, GetAutoMLRunOutput } from "../dto/automl-run.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { AutomlRunRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetAutoMLRun {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly automlRun: AutomlRunRepository
  ) {}

  async execute(input: GetAutoMLRunInput): Promise<GetAutoMLRunOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.amlId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).runId) {
      throw new ValidationError("runId is required");
    }
    const runId = (input as any).runId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.automlRun.getAutoMLRun({ runId: runId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${runId}`);
    }

    return entity as GetAutoMLRunOutput;
  }
}
