/**
 * ExecuteListAutoMLRuns - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: automl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAutoMLRuns Use Case
 *
 * DDD: Application use case for list AutomlRun.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAutoMLRunsInput, ListAutoMLRunsOutput } from "../dto/automl-run.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { AutomlRunRepository } from "../ports";

export class ExecuteListAutoMLRuns {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly automlRun: AutomlRunRepository
  ) {}

  async execute(input: ListAutoMLRunsInput): Promise<ListAutoMLRunsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.amlId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.automlRun.listAutoMLRuns({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAutoMLRunsOutput;
  }
}
