/**
 * ExecuteListCandidates - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: automl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListCandidates Use Case
 *
 * DDD: Application use case for list Candidate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListCandidatesInput, ListCandidatesOutput } from "../dto/candidate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { CandidateRepository } from "../ports";

export class ExecuteListCandidates {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly candidate: CandidateRepository
  ) {}

  async execute(input: ListCandidatesInput): Promise<ListCandidatesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.amlId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.candidate.listCandidates({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListCandidatesOutput;
  }
}
