/**
 * ExecuteStartAutoMLRun - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: automl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteStartAutoMLRun Use Case
 *
 * DDD: Application use case for create AutomlRun.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { StartAutoMLRunInput, StartAutoMLRunOutput } from "../dto/automl-run.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { AutomlRunRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteStartAutoMLRun {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly automlRun: AutomlRunRepository
  ) {}

  async execute(input: StartAutoMLRunInput): Promise<StartAutoMLRunOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.amlId();

    // All field names extracted from OpenAPI spec: maxCandidates, searchBudgetMinutes
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    // No required field validations    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (automl domain)
    const entityId = this.idGenerator.amlId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.automlRun.startAutoMLRun({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as StartAutoMLRunOutput;
  }
}
