/**
 * GetCandidate handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: automl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getCandidate } from "@scorvia/api-server/domains/automl/handlers";
import type { AutomlDDDDependencies } from "@scorvia/api-server/domains/automl";
import { createCandidate as createCandidateEntity } from "@scorvia/factories/automl";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@scorvia/tests/shared";
import { AUTOML_USE_CASES } from "../__factories__/use-cases.js";

describe("GetCandidate", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AutomlDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AutomlDDDDependencies>(
      AUTOML_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createCandidateEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetCandidate, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { candidateId: entity.id };

    await getCandidate(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetCandidate.execute).toHaveBeenCalledWith(expect.objectContaining({ candidateId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { candidateId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetCandidate, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getCandidate(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
