/**
 * ListCandidates handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: automl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listCandidates } from "@scorvia/api-server/domains/automl/handlers";
import type { AutomlDDDDependencies } from "@scorvia/api-server/domains/automl";
import { createCandidate as createCandidateEntity } from "@scorvia/factories/automl";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@scorvia/tests/shared";
import { AUTOML_USE_CASES } from "../__factories__/use-cases.js";

describe("ListCandidates", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AutomlDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AutomlDDDDependencies>(
      AUTOML_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createCandidateEntity({ orgId }),
      createCandidateEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListCandidates, "execute").mockResolvedValue(useCaseResult);

    await listCandidates(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListCandidates.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
