/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @scorvia/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@scorvia/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@scorvia/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@scorvia/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@scorvia/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@scorvia/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _audits from "./audits/index.js";
import * as _automl from "./automl/index.js";
import * as _evaluations from "./evaluations/index.js";
import * as _identity from "./identity/index.js";
import * as _monitoring from "./monitoring/index.js";
import * as _policy from "./policy/index.js";
import * as _projects from "./projects/index.js";
import * as _promotions from "./promotions/index.js";
import * as _referrals from "./referrals/index.js";
import * as _scoring from "./scoring/index.js";

// Export as namespaces
export const _shared = __shared;
export const audits = _audits;
export const automl = _automl;
export const evaluations = _evaluations;
export const identity = _identity;
export const monitoring = _monitoring;
export const policy = _policy;
export const projects = _projects;
export const promotions = _promotions;
export const referrals = _referrals;
export const scoring = _scoring;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@scorvia/core"; activity.types.*
//   - Direct exports: import * from "@scorvia/core/activity/types/index.js"
//   - Direct exports: import * from "@scorvia/core/activity/repositories/index.js"
//   - Direct exports: import * from "@scorvia/core/activity/models/index.js"
//   - Direct exports: import * from "@scorvia/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Audits Service
export { schemas as AuditsSchemas } from "./audits/schemas/audits.schemas.js";

// Automl Service
export { schemas as AutomlSchemas } from "./automl/schemas/automl.schemas.js";

// Evaluations Service
export { schemas as EvaluationsSchemas } from "./evaluations/schemas/evaluations.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Monitoring Service
export { schemas as MonitoringSchemas } from "./monitoring/schemas/monitoring.schemas.js";

// Policy Service
export { schemas as PolicySchemas } from "./policy/schemas/policy.schemas.js";

// Projects Service
export { schemas as ProjectsSchemas } from "./projects/schemas/projects.schemas.js";

// Promotions Service
export { schemas as PromotionsSchemas } from "./promotions/schemas/promotions.schemas.js";

// Referrals Service
export { schemas as ReferralsSchemas } from "./referrals/schemas/referrals.schemas.js";

// Scoring Service
export { schemas as ScoringSchemas } from "./scoring/schemas/scoring.schemas.js";

