/**
 * ExecuteListDeployments - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDeployments Use Case
 *
 * DDD: Application use case for list Deployment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDeploymentsInput, ListDeploymentsOutput } from "../dto/deployment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { DeploymentRepository } from "../ports";

export class ExecuteListDeployments {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly deployment: DeploymentRepository
  ) {}

  async execute(input: ListDeploymentsInput): Promise<ListDeploymentsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.deployment.listDeployments({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDeploymentsOutput;
  }
}
