/**
 * ExecuteScoreApplication - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteScoreApplication Use Case
 *
 * DDD: Application use case for get Score.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ScoreApplicationInput, ScoreApplicationOutput } from "../dto/score.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { ScoreRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteScoreApplication {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly score: ScoreRepository
  ) {}

  async execute(input: ScoreApplicationInput): Promise<ScoreApplicationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scrId();

    // All field names extracted from OpenAPI spec: applicationId, deploymentId, features
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).applicationId) {
      throw new ValidationError("applicationId is required");
    }
    const applicationId = (input as any).applicationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.score.scoreApplication({ applicationId: applicationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${applicationId}`);
    }

    return entity as ScoreApplicationOutput;
  }
}
