/**
 * PolicyMap DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyMap DTOs
 *
 * DDD: Application DTOs for PolicyMap use cases.
 */

import type { CreatePolicyMapRequestInput, GetPolicyMapParams, ListPolicyMapsParams } from "@scorvia/core/policy/types";

export type ListPolicyMapsInput = ListPolicyMapsParams;

export type CreatePolicyMapInput = CreatePolicyMapRequestInput;

export type GetPolicyMapInput = GetPolicyMapParams;

export type ListPolicyMapsOutput = {};

export type CreatePolicyMapOutput = {};

export type GetPolicyMapOutput = {};
