/**
 * IncidentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IncidentRepository Port
 *
 * DDD: Application port for incidentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListMonitoringIncidentsInput, ListMonitoringIncidentsOutput, OpenMonitoringIncidentInput, OpenMonitoringIncidentOutput } from "../dto/incident.dto";
export interface IncidentRepository {
  listMonitoringIncidents(input: ListMonitoringIncidentsInput): Promise<ListMonitoringIncidentsOutput>;
  openMonitoringIncident(input: OpenMonitoringIncidentInput): Promise<OpenMonitoringIncidentOutput>;
}

export type { ListMonitoringIncidentsInput, ListMonitoringIncidentsOutput, OpenMonitoringIncidentInput, OpenMonitoringIncidentOutput } from "../dto/incident.dto";
