/**
 * ExecuteDisposeMonitoringIncident - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDisposeMonitoringIncident Use Case
 *
 * DDD: Application use case for get Dispose.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DisposeMonitoringIncidentInput, DisposeMonitoringIncidentOutput } from "../dto/dispose.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { DisposeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDisposeMonitoringIncident {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dispose: DisposeRepository
  ) {}

  async execute(input: DisposeMonitoringIncidentInput): Promise<DisposeMonitoringIncidentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.monId();

    // All field names extracted from OpenAPI spec: disposition, status
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).incidentId) {
      throw new ValidationError("incidentId is required");
    }
    const incidentId = (input as any).incidentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.dispose.disposeMonitoringIncident({ incidentId: incidentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${incidentId}`);
    }

    return entity as DisposeMonitoringIncidentOutput;
  }
}
