/**
 * ExecuteListMonitoringIncidents - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListMonitoringIncidents Use Case
 *
 * DDD: Application use case for list Incident.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListMonitoringIncidentsInput, ListMonitoringIncidentsOutput } from "../dto/incident.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { IncidentRepository } from "../ports";

export class ExecuteListMonitoringIncidents {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly incident: IncidentRepository
  ) {}

  async execute(input: ListMonitoringIncidentsInput): Promise<ListMonitoringIncidentsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.monId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.incident.listMonitoringIncidents({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListMonitoringIncidentsOutput;
  }
}
