/**
 * Handlers for PolicyMap
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PolicyDomainModule } from "../dependencies/policy-ddd.dependencies.js";
import type { CreatePolicyMapInput, GetPolicyMapInput, ListPolicyMapsInput } from "@scorvia/services/policy";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/policy-maps
 * Operation: listPolicyMaps
 */
export async function listPolicyMaps(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PolicyDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPolicyMapsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.maps.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/policy-maps
 * Operation: createPolicyMap
 */
export async function createPolicyMap(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: PolicyDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreatePolicyMapInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.maps.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/policy-maps/{policyMapId}
 * Operation: getPolicyMap
 */
export async function getPolicyMap(
  request: FastifyRequest<{ Params: { policyMapId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PolicyDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPolicyMapInput = {
    policyMapId: request.params.policyMapId,
  };
  const result = await deps.useCases.maps.get.execute(input);
  return reply.code(200).send(result);
}


