/**
 * Handlers for Publish
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PolicyDomainModule } from "../dependencies/policy-ddd.dependencies.js";
import type { PublishPolicyMapInput } from "@scorvia/services/policy";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/policy-maps/{policyMapId}/publish
 * Operation: publishPolicyMap
 */
export async function publishPolicyMap(
  request: FastifyRequest<{ Params: { policyMapId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PolicyDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: PublishPolicyMapInput = {
    policyMapId: request.params.policyMapId,
  };
  const result = await deps.useCases.publishes.get.execute(input);
  return reply.code(200).send(result);
}


