/**
 * Repository interface for Deployment
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DeploymentEntity
} from "../models/deployment.entity.js";
import type {
  ListDeploymentsParams
} from "../types/index.js";
/**
 * DeploymentRepository Interface
 */
export interface DeploymentRepository extends ReadRepository<DeploymentEntity, string, ListDeploymentsParams> {

}
