/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Policy Domain Use Cases
 * 
 * List of all use case names for the policy domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const POLICY_USE_CASES = [
  "executeCreatePolicyMap",
  "executeGetPolicyMap",
  "executeListPolicyMaps",
  "executePublishPolicyMap",
  "executeSimulatePolicyMap"
] as const;
