/**
 * DecideRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DecideRepository Port
 *
 * DDD: Application port for deciderepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DecidePromotionInput, DecidePromotionOutput } from "../dto/decide.dto";
export interface DecideRepository {
  decidePromotion(input: DecidePromotionInput): Promise<DecidePromotionOutput>;
}

export type { DecidePromotionInput, DecidePromotionOutput } from "../dto/decide.dto";
