/**
 * PromotionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PromotionRepository Port
 *
 * DDD: Application port for promotionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetPromotionInput, GetPromotionOutput, ListPromotionsInput, ListPromotionsOutput, RequestPromotionInput, RequestPromotionOutput } from "../dto/promotion.dto";
export interface PromotionRepository {
  requestPromotion(input: RequestPromotionInput): Promise<RequestPromotionOutput>;
  listPromotions(input: ListPromotionsInput): Promise<ListPromotionsOutput>;
  getPromotion(input: GetPromotionInput): Promise<GetPromotionOutput>;
}

export type { GetPromotionInput, GetPromotionOutput, ListPromotionsInput, ListPromotionsOutput, RequestPromotionInput, RequestPromotionOutput } from "../dto/promotion.dto";
