/**
 * Resolve Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/referrals.openapi.types.js";
import { schemas } from "../schemas/referrals.schemas.js";

/**
 * Entity: ResolveEntity
 * Description: Represents the Resolve domain model.
 * Source: schemas.Referral
 * Type: Persisted Entity (x-dynamodb)
 */
export const ResolveEntitySchema = schemas.Referral;
export type ResolveEntity = components["schemas"]["Referral"];
