/**
 * GetPromotion handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getPromotion } from "@scorvia/api-server/domains/promotions/handlers";
import type { PromotionsDDDDependencies } from "@scorvia/api-server/domains/promotions";
import { createPromotion as createPromotionEntity } from "@scorvia/factories/promotions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@scorvia/tests/shared";
import { PROMOTIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetPromotion", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PromotionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PromotionsDDDDependencies>(
      PROMOTIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createPromotionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetPromotion, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { promotionId: entity.id };

    await getPromotion(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetPromotion.execute).toHaveBeenCalledWith(expect.objectContaining({ promotionId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { promotionId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetPromotion, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getPromotion(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
