/**
 * RequestPromotion handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { requestPromotion } from "@scorvia/api-server/domains/promotions/handlers";
import type { PromotionsDDDDependencies } from "@scorvia/api-server/domains/promotions";
import { createPromotion as createPromotionEntity } from "@scorvia/factories/promotions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@scorvia/tests/shared";
import { PROMOTIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("RequestPromotion", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PromotionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PromotionsDDDDependencies>(
      PROMOTIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createPromotionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRequestPromotion, "execute").mockResolvedValue(useCaseResult);

    await requestPromotion(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRequestPromotion.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
