/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAuditsDomainModule } from "./audits/dependencies/audits-ddd.dependencies.js";
export { buildAutomlDomainModule } from "./automl/dependencies/automl-ddd.dependencies.js";
export { buildEvaluationsDomainModule } from "./evaluations/dependencies/evaluations-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildMonitoringDomainModule } from "./monitoring/dependencies/monitoring-ddd.dependencies.js";
export { buildPolicyDomainModule } from "./policy/dependencies/policy-ddd.dependencies.js";
export { buildProjectsDomainModule } from "./projects/dependencies/projects-ddd.dependencies.js";
export { buildPromotionsDomainModule } from "./promotions/dependencies/promotions-ddd.dependencies.js";
export { buildReferralsDomainModule } from "./referrals/dependencies/referrals-ddd.dependencies.js";
export { buildScoringDomainModule } from "./scoring/dependencies/scoring-ddd.dependencies.js";

// Export all domain dependency types
export type { AuditsDomainModule } from "./audits/dependencies/audits-ddd.dependencies.js";
export type { AutomlDomainModule } from "./automl/dependencies/automl-ddd.dependencies.js";
export type { EvaluationsDomainModule } from "./evaluations/dependencies/evaluations-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { MonitoringDomainModule } from "./monitoring/dependencies/monitoring-ddd.dependencies.js";
export type { PolicyDomainModule } from "./policy/dependencies/policy-ddd.dependencies.js";
export type { ProjectsDomainModule } from "./projects/dependencies/projects-ddd.dependencies.js";
export type { PromotionsDomainModule } from "./promotions/dependencies/promotions-ddd.dependencies.js";
export type { ReferralsDomainModule } from "./referrals/dependencies/referrals-ddd.dependencies.js";
export type { ScoringDomainModule } from "./scoring/dependencies/scoring-ddd.dependencies.js";
