/**
 * Deployment Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DeploymentEntity } from "@scorvia/core/scoring/models/index.js";
import { scoringSchemas } from "@scorvia/core/scoring";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "scr";

export function createDeployment(overrides: Partial<DeploymentEntity> = {}) {
  const raw = {
    id: overrides.id ?? `dep_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    active: overrides.active ?? faker.datatype.boolean(),
    environment: overrides.environment ?? "poc",
    modelId: overrides.modelId ?? faker.string.uuid(),
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return scoringSchemas.ProductionDeployment.parse(raw);
}

export function deploymentBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDeployment(overrides));
}
