/**
 * CandidateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: automl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CandidateRepository Port
 *
 * DDD: Application port for candidaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCandidateInput, GetCandidateOutput, ListCandidatesInput, ListCandidatesOutput } from "../dto/candidate.dto";
export interface CandidateRepository {
  listCandidates(input: ListCandidatesInput): Promise<ListCandidatesOutput>;
  getCandidate(input: GetCandidateInput): Promise<GetCandidateOutput>;
}

export type { GetCandidateInput, GetCandidateOutput, ListCandidatesInput, ListCandidatesOutput } from "../dto/candidate.dto";
