/**
 * ExportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExportRepository Port
 *
 * DDD: Application port for exportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateScorviaAuditExportInput, CreateScorviaAuditExportOutput, GetAuditExportInput, GetAuditExportOutput, ListAuditExportsInput, ListAuditExportsOutput } from "../dto/export.dto";
export interface ExportRepository {
  listAuditExports(input: ListAuditExportsInput): Promise<ListAuditExportsOutput>;
  createScorviaAuditExport(input: CreateScorviaAuditExportInput): Promise<CreateScorviaAuditExportOutput>;
  getAuditExport(input: GetAuditExportInput): Promise<GetAuditExportOutput>;
}

export type { CreateScorviaAuditExportInput, CreateScorviaAuditExportOutput, GetAuditExportInput, GetAuditExportOutput, ListAuditExportsInput, ListAuditExportsOutput } from "../dto/export.dto";
