/**
 * ExecuteListAuditExports - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAuditExports Use Case
 *
 * DDD: Application use case for list Export.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAuditExportsInput, ListAuditExportsOutput } from "../dto/export.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { ExportRepository } from "../ports";

export class ExecuteListAuditExports {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exportRepo: ExportRepository
  ) {}

  async execute(input: ListAuditExportsInput): Promise<ListAuditExportsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.audId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.exportRepo.listAuditExports({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAuditExportsOutput;
  }
}
