/**
 * GetPolicyMap DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetPolicyMapParams } from "@scorvia/core/policy";

export function createGetPolicyMapRequest(overrides: Partial<GetPolicyMapParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
