/**
 * ListPolicyMap DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListPolicyMapsParams } from "@scorvia/core/policy";

export function createListPolicyMapRequest(overrides: Partial<ListPolicyMapsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
