/**
 * Promotion DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Promotion DTOs
 *
 * DDD: Application DTOs for Promotion use cases.
 */

import type { GetPromotionParams, ListPromotionsParams, RequestPromotionParams, RequestPromotionRequestInput } from "@scorvia/core/promotions/types";

export type RequestPromotionInput = RequestPromotionParams & RequestPromotionRequestInput;

export type ListPromotionsInput = ListPromotionsParams;

export type GetPromotionInput = GetPromotionParams;

export type RequestPromotionOutput = {};

export type ListPromotionsOutput = {};

export type GetPromotionOutput = {};
