/**
 * AttachInterpretabilityPack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { attachInterpretabilityPack } from "@scorvia/api-server/domains/evaluations/handlers";
import type { EvaluationsDDDDependencies } from "@scorvia/api-server/domains/evaluations";
import { createInterpretabilityPack as createInterpretabilityPackEntity } from "@scorvia/factories/evaluations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@scorvia/tests/shared";
import { EVALUATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("AttachInterpretabilityPack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EvaluationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EvaluationsDDDDependencies>(
      EVALUATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createInterpretabilityPackEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeAttachInterpretabilityPack, "execute").mockResolvedValue(useCaseResult);

    await attachInterpretabilityPack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeAttachInterpretabilityPack.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
