/**
 * AutomlRun Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: automl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/automl.openapi.types.js";
import { schemas } from "../schemas/automl.schemas.js";

/**
 * Entity: AutomlRunEntity
 * Description: Represents the AutomlRun domain model.
 * Source: schemas.AutoMLRun
 * Type: Persisted Entity (x-dynamodb)
 */
export const AutomlRunEntitySchema = schemas.AutoMLRun;
export type AutomlRunEntity = components["schemas"]["AutoMLRun"];
