/**
 * Models barrel export - All Projects entities
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./dataset.entity.js";
export * from "./project.entity.js";
