/**
 * ExecuteCreatePolicyMap - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreatePolicyMap Use Case
 *
 * DDD: Application use case for create PolicyMap.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreatePolicyMapInput, CreatePolicyMapOutput } from "../dto/policy-map.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { PolicyMapRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreatePolicyMap {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policyMap: PolicyMapRepository
  ) {}

  async execute(input: CreatePolicyMapInput): Promise<CreatePolicyMapOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: bands, name, projectId, referralRequired
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.bands) {
      throw new ValidationError("bands is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (policy domain)
    const entityId = this.idGenerator.polId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.policyMap.createPolicyMap({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreatePolicyMapOutput;
  }
}
