/**
 * Routes for Score
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { scoreApplication } from "../handlers/score.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function scoreRoutes(fastify: FastifyInstance) {
  // POST /v1/scoring/score (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/scoring/score",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getScoringDependenciesForRequest();
        await scoreApplication(request, reply, deps);
      });
    }
  );


}
