/**
 * ListMonitoringIncidents handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listMonitoringIncidents } from "@scorvia/api-server/domains/monitoring/handlers";
import type { MonitoringDDDDependencies } from "@scorvia/api-server/domains/monitoring";
import { createIncident as createIncidentEntity } from "@scorvia/factories/monitoring";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@scorvia/tests/shared";
import { MONITORING_USE_CASES } from "../__factories__/use-cases.js";

describe("ListMonitoringIncidents", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: MonitoringDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<MonitoringDDDDependencies>(
      MONITORING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createIncidentEntity({ orgId }),
      createIncidentEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListMonitoringIncidents, "execute").mockResolvedValue(useCaseResult);

    await listMonitoringIncidents(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListMonitoringIncidents.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
