/**
 * Resolve Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ResolveEntity } from "@scorvia/core/referrals/models/index.js";
import { referralsSchemas } from "@scorvia/core/referrals";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ref";

export function createResolve(overrides: Partial<ResolveEntity> = {}) {
  const raw = {
    id: overrides.id ?? `ref_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    applicationId: overrides.applicationId ?? faker.string.uuid(),
    status: overrides.status ?? "open",
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return referralsSchemas.Referral.parse(raw);
}

export function resolveBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createResolve(overrides));
}
