/**
 * Candidate Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: automl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CandidateEntity } from "@scorvia/core/automl/models/index.js";
import { automlSchemas } from "@scorvia/core/automl";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "aml";

export function createCandidate(overrides: Partial<CandidateEntity> = {}) {
  const raw = {
    id: overrides.id ?? `cnd_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    algorithm: overrides.algorithm ?? faker.lorem.word(),
    runId: overrides.runId ?? `aml_${ulid().toLowerCase()}`,
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return automlSchemas.CandidateModel.parse(raw);
}

export function candidateBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCandidate(overrides));
}
