/**
 * PolicyMapRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyMapRepository Port
 *
 * DDD: Application port for policymaprepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreatePolicyMapInput, CreatePolicyMapOutput, GetPolicyMapInput, GetPolicyMapOutput, ListPolicyMapsInput, ListPolicyMapsOutput } from "../dto/policy-map.dto";
export interface PolicyMapRepository {
  listPolicyMaps(input: ListPolicyMapsInput): Promise<ListPolicyMapsOutput>;
  createPolicyMap(input: CreatePolicyMapInput): Promise<CreatePolicyMapOutput>;
  getPolicyMap(input: GetPolicyMapInput): Promise<GetPolicyMapOutput>;
}

export type { CreatePolicyMapInput, CreatePolicyMapOutput, GetPolicyMapInput, GetPolicyMapOutput, ListPolicyMapsInput, ListPolicyMapsOutput } from "../dto/policy-map.dto";
