/**
 * SimulateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SimulateRepository Port
 *
 * DDD: Application port for simulaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SimulatePolicyMapInput, SimulatePolicyMapOutput } from "../dto/simulate.dto";
export interface SimulateRepository {
  simulatePolicyMap(input: SimulatePolicyMapInput): Promise<SimulatePolicyMapOutput>;
}

export type { SimulatePolicyMapInput, SimulatePolicyMapOutput } from "../dto/simulate.dto";
