/**
 * InterpretabilityPack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InterpretabilityPack DTOs
 *
 * DDD: Application DTOs for InterpretabilityPack use cases.
 */

import type { AttachInterpretabilityPackParams, AttachInterpretabilityPackRequestInput } from "@scorvia/core/evaluations/types";

export type AttachInterpretabilityPackInput = AttachInterpretabilityPackParams & AttachInterpretabilityPackRequestInput;

export type AttachInterpretabilityPackOutput = {};
