/**
 * Scoring DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Scoring Domain Module - Composition root
 *
 * DDD: Composition root for scoring domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DeploymentRepositoryAdapter,
  ScoreRepositoryAdapter,
} from "@scorvia/adapters/scoring";
import { getIdGeneratorService } from "@scorvia/adapters";
import type { AdapterDynamoDBClient } from "@scorvia/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteListDeployments,
  ExecuteScoreApplication,
} from "@scorvia/services/scoring/usecases";
// Ports (interfaces)
import type {
  DeploymentRepository,
  ScoreRepository,
} from "@scorvia/services/scoring/ports";

export interface ScoringDomainModule {
  repos: {
    deployments: DeploymentRepository;
    scores: ScoreRepository;
  };
  useCases: {
    deployments: {
      list: ExecuteListDeployments;
    };
    scores: {
      get: ExecuteScoreApplication;
    };
  };
}

export function buildScoringDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ScoringDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      deployments?: DeploymentRepository;
      scores?: ScoreRepository;
    } = {};

    obj.deployments = new DeploymentRepositoryAdapter(dynamoClient);
    obj.scores = new ScoreRepositoryAdapter(dynamoClient);
    return {
      deployments: obj.deployments!,
      scores: obj.scores!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    deployments: {
      list: new ExecuteListDeployments(executionContext, idGenerator, repos.deployments),
    },
    scores: {
      get: new ExecuteScoreApplication(executionContext, idGenerator, repos.scores),
    },
  };
  return { repos, useCases: useCases as ScoringDomainModule["useCases"] };
}
