/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { policyMapRoutes } from "./policy-map.routes.js";
export { publishRoutes } from "./publish.routes.js";
export { simulateRoutes } from "./simulate.routes.js";
