/**
 * Routes for Publish
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { publishPolicyMap } from "../handlers/publish.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function publishRoutes(fastify: FastifyInstance) {
  // POST /v1/policy-maps/{policyMapId}/publish (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/policy-maps/:policyMapId/publish",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyMapId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPolicyDependenciesForRequest();
        await publishPolicyMap(request, reply, deps);
      });
    }
  );


}
