/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { evaluationRoutes } from "./evaluation.routes.js";
export { interpretabilityPackRoutes } from "./interpretability-pack.routes.js";
