/**
 * Routes for InterpretabilityPack
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { attachInterpretabilityPack } from "../handlers/interpretability-pack.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function interpretabilityPackRoutes(fastify: FastifyInstance) {
  // POST /v1/candidates/{candidateId}/interpretability-packs (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/candidates/:candidateId/interpretability-packs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvaluationsDependenciesForRequest();
        await attachInterpretabilityPack(request, reply, deps);
      });
    }
  );


}
