/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Promotions Domain Use Cases
 * 
 * List of all use case names for the promotions domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const PROMOTIONS_USE_CASES = [
  "executeDecidePromotion",
  "executeGetPromotion",
  "executeListPromotions",
  "executeRequestPromotion"
] as const;
