/**
 * ListProject DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListCreditProjectsParams } from "@scorvia/core/projects";

export function createListProjectRequest(overrides: Partial<ListCreditProjectsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
