/**
 * ListIncident DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListMonitoringIncidentsParams } from "@scorvia/core/monitoring";

export function createListIncidentRequest(overrides: Partial<ListMonitoringIncidentsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
