/**
 * InterpretabilityPackRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InterpretabilityPackRepository Port
 *
 * DDD: Application port for interpretabilitypackrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AttachInterpretabilityPackInput, AttachInterpretabilityPackOutput } from "../dto/interpretability-pack.dto";
export interface InterpretabilityPackRepository {
  attachInterpretabilityPack(input: AttachInterpretabilityPackInput): Promise<AttachInterpretabilityPackOutput>;
}

export type { AttachInterpretabilityPackInput, AttachInterpretabilityPackOutput } from "../dto/interpretability-pack.dto";
