/**
 * Projects DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Projects Domain Module - Composition root
 *
 * DDD: Composition root for projects domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DatasetRepositoryAdapter,
  ProjectRepositoryAdapter,
} from "@scorvia/adapters/projects";
import { getIdGeneratorService } from "@scorvia/adapters";
import type { AdapterDynamoDBClient } from "@scorvia/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAttachDataset,
  ExecuteCreateCreditProject,
  ExecuteGetCreditProject,
  ExecuteListCreditProjects,
} from "@scorvia/services/projects/usecases";
// Ports (interfaces)
import type {
  DatasetRepository,
  ProjectRepository,
} from "@scorvia/services/projects/ports";

export interface ProjectsDomainModule {
  repos: {
    datasets: DatasetRepository;
    projects: ProjectRepository;
  };
  useCases: {
    datasets: {
      get: ExecuteAttachDataset;
    };
    projects: {
      create: ExecuteCreateCreditProject;
      get: ExecuteGetCreditProject;
      list: ExecuteListCreditProjects;
    };
  };
}

export function buildProjectsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ProjectsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      datasets?: DatasetRepository;
      projects?: ProjectRepository;
    } = {};

    obj.datasets = new DatasetRepositoryAdapter(dynamoClient);
    obj.projects = new ProjectRepositoryAdapter(dynamoClient);
    return {
      datasets: obj.datasets!,
      projects: obj.projects!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    datasets: {
      get: new ExecuteAttachDataset(executionContext, idGenerator, repos.datasets),
    },
    projects: {
      create: new ExecuteCreateCreditProject(executionContext, idGenerator, repos.projects),
      get: new ExecuteGetCreditProject(executionContext, idGenerator, repos.projects),
      list: new ExecuteListCreditProjects(executionContext, idGenerator, repos.projects),
    },
  };
  return { repos, useCases: useCases as ProjectsDomainModule["useCases"] };
}
