/**
 * PromotionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PromotionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PromotionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PromotionRepository,
} from "@scorvia/services/promotions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PromotionRepositoryDdb } from "./promotion-repository.ddb.js";

/**
 * PromotionRepositoryAdapter
 *
 * Implements PromotionRepository port for infrastructure layer.
 */
export class PromotionRepositoryAdapter implements PromotionRepository {
  private readonly ddb: PromotionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PromotionRepositoryDdb(this.dynamoClient);
  }

  async requestPromotion(input: Parameters<PromotionRepository['requestPromotion']>[0]): Promise<Awaited<ReturnType<PromotionRepository['requestPromotion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.requestPromotion(input);
  }

  async listPromotions(input: Parameters<PromotionRepository['listPromotions']>[0]): Promise<Awaited<ReturnType<PromotionRepository['listPromotions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPromotions(input);
  }

  async getPromotion(input: Parameters<PromotionRepository['getPromotion']>[0]): Promise<Awaited<ReturnType<PromotionRepository['getPromotion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getPromotion(input);
  }
}
