/**
 * Routes for AutomlRun
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: automl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getAutoMLRun, listAutoMLRuns, startAutoMLRun } from "../handlers/automl-run.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function automlRunRoutes(fastify: FastifyInstance) {
  // GET /v1/automl-runs/{runId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/automl-runs/:runId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { runId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAutomlDependenciesForRequest();
        await getAutoMLRun(request, reply, deps);
      });
    }
  );


  // GET /v1/projects/{projectId}/automl-runs (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/projects/:projectId/automl-runs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAutomlDependenciesForRequest();
        await listAutoMLRuns(request, reply, deps);
      });
    }
  );


  // POST /v1/projects/{projectId}/automl-runs (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/projects/:projectId/automl-runs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAutomlDependenciesForRequest();
        await startAutoMLRun(request, reply, deps);
      });
    }
  );


}
