/**
 * ExecuteGetReferral - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetReferral Use Case
 *
 * DDD: Application use case for get Referral.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetReferralInput, GetReferralOutput } from "../dto/referral.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { ReferralRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetReferral {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly referral: ReferralRepository
  ) {}

  async execute(input: GetReferralInput): Promise<GetReferralOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.refId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).referralId) {
      throw new ValidationError("referralId is required");
    }
    const referralId = (input as any).referralId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.referral.getReferral({ referralId: referralId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${referralId}`);
    }

    return entity as GetReferralOutput;
  }
}
