/**
 * ExecuteListReferrals - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListReferrals Use Case
 *
 * DDD: Application use case for list Referral.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListReferralsInput, ListReferralsOutput } from "../dto/referral.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { ReferralRepository } from "../ports";

export class ExecuteListReferrals {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly referral: ReferralRepository
  ) {}

  async execute(input: ListReferralsInput): Promise<ListReferralsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.refId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.referral.listReferrals({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListReferralsOutput;
  }
}
