/**
 * ReferralRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReferralRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReferralRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReferralRepository,
} from "@scorvia/services/referrals";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReferralRepositoryDdb } from "./referral-repository.ddb.js";

/**
 * ReferralRepositoryAdapter
 *
 * Implements ReferralRepository port for infrastructure layer.
 */
export class ReferralRepositoryAdapter implements ReferralRepository {
  private readonly ddb: ReferralRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReferralRepositoryDdb(this.dynamoClient);
  }

  async listReferrals(input: Parameters<ReferralRepository['listReferrals']>[0]): Promise<Awaited<ReturnType<ReferralRepository['listReferrals']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listReferrals(input);
  }

  async getReferral(input: Parameters<ReferralRepository['getReferral']>[0]): Promise<Awaited<ReturnType<ReferralRepository['getReferral']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getReferral(input);
  }
}
