/**
 * Handlers for Project
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ProjectsDomainModule } from "../dependencies/projects-ddd.dependencies.js";
import type { CreateCreditProjectInput, GetCreditProjectInput, ListCreditProjectsInput } from "@scorvia/services/projects";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/projects
 * Operation: listCreditProjects
 */
export async function listCreditProjects(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ProjectsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCreditProjectsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.projects.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/projects
 * Operation: createCreditProject
 */
export async function createCreditProject(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ProjectsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateCreditProjectInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.projects.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/projects/{projectId}
 * Operation: getCreditProject
 */
export async function getCreditProject(
  request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ProjectsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCreditProjectInput = {
    projectId: request.params.projectId,
  };
  const result = await deps.useCases.projects.get.execute(input);
  return reply.code(200).send(result);
}


