/**
 * Referral DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Referral DTOs
 *
 * DDD: Application DTOs for Referral use cases.
 */

import type { GetReferralParams, ListReferralsParams } from "@scorvia/core/referrals/types";

export type ListReferralsInput = ListReferralsParams;

export type GetReferralInput = GetReferralParams;

export type ListReferralsOutput = {};

export type GetReferralOutput = {};
