/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: promotions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the promotions domain.
 * Use these factories in tests to create test data.
 */

export { createDecide } from "./decide/entity/decide.entity.factory.js";
export { createPromotion } from "./promotion/entity/promotion.entity.factory.js";
