/**
 * ExecuteGetCreditProject - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetCreditProject Use Case
 *
 * DDD: Application use case for get Project.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetCreditProjectInput, GetCreditProjectOutput } from "../dto/project.dto";
import type { ExecutionContextService, IdGeneratorService } from "@scorvia/services/_shared/index.js";
import type { ProjectRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetCreditProject {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly project: ProjectRepository
  ) {}

  async execute(input: GetCreditProjectInput): Promise<GetCreditProjectOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prjId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).projectId) {
      throw new ValidationError("projectId is required");
    }
    const projectId = (input as any).projectId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.project.getCreditProject({ projectId: projectId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${projectId}`);
    }

    return entity as GetCreditProjectOutput;
  }
}
